# Generated by Django 5.0.3 on 2024-03-19 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_clienteadjudicado_direccion_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_gasto',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.cliente'),
        ),
    ]
