# Generated by Django 5.0.3 on 2024-03-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=11, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('rnc', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('posicion', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='client.cliente')),
            ],
        ),
    ]
