# Generated by Django 5.0.3 on 2024-03-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAdjudicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rnc_cedula', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_adjudicados', to='client.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
