# Generated by Django 5.0.3 on 2024-03-19 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clienteadjudicado_delete_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteadjudicado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clienteadjudicado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='clienteadjudicado',
            name='adjudicado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clientes_adjudicados', to='client.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteadjudicado',
            name='correo',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteadjudicado',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
