# Generated by Django 5.0.3 on 2024-03-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registropago',
            name='cliente',
        ),
    ]
