# Generated by Django 5.0.3 on 2024-03-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
