# Generated by Django 5.0.3 on 2024-03-19 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_clienteadjudicado_direccion_and_more'),
        ('facturacion', '0003_remove_factura_pedido_delete_pedido'),
        ('inventario', '0002_alter_categoriaproducto_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='numero',
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.cliente'),
        ),
        migrations.CreateModel(
            name='ElementoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='facturacion.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
