# Generated by Django 5.0.3 on 2024-03-19 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_clienteadjudicado_direccion_and_more'),
        ('facturacion', '0004_remove_pago_factura_remove_factura_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clienteadjudicado'),
        ),
    ]
