# Generated by Django 5.0.3 on 2024-03-18 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_cliente'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.cliente'),
        ),
    ]
